version: '3.8'

x-container-name: &container-name
  container_name: template-rails-api-${SERVICE}

services:
  web:
    <<: *container-name
    build:
      context: .
      dockerfile: Dockerfile
    command: ["sh", "-c", "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"]
    image: rails-app
    ports:
      - "3000:3000"
    environment:
      - SERVICE=web
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle
    env_file: development.env
    depends_on:
      - db
      - db-test

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: template_rails_development
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
      SERVICE: db
    volumes:
      - db_data:/var/lib/mysql
  
  db-test:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: template_rails_test
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
      SERVICE: db-test
    ports:
      - '3307:3306'
    volumes:
      - db_test_data:/var/lib/mysql

volumes:
  gem_cache:
  db_data:
  db_test_data:
