services:
  web:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace
      - gem_cache:/workspace/vendor/bundle
    env_file: ../.env.development
    tty: true
    stdin_open: true
    command: ["sleep", "infinity"]
    depends_on:
      - db

  db:
    image: mysql:8
    env_file: ../.env.development
    volumes:
      - db_data:/var/lib/mysql

volumes:
  gem_cache:
  db_data:
