default: &default
  adapter: mysql2
  encoding: utf8mb4
  host: <%= ENV.fetch("DATABASE_HOST") %>
  username: <%= ENV.fetch("DATABASE_USER") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>

development:
  <<: *default
  database: template-rails-api_development

test:
  <<: *default
  database: template-rails-api_test

production:
  <<: *default
  database: template-rails-api_production
